#!/usr/bin/env bash

screenshot_dir="${HOME}/Pictures/Awesomeshot"
file_name="Screenshot_`date "+%Y-%m-%d_%H-%M-%S"`.png"
full_file_name="${screenshot_dir}/${file_name}"

function convertTitleBar() {
  g="#27C93F" #green
  y="#FFBD2E" #yellow
  r="#FF5F56" #red
  b="#282C34" #black

  # width_img=$(magick ${full_file_name} - format "%w" info:)
  # height_img=$(magick ${full_file_name} - format "%h" info:)
  # if (( ${width_img} > ${height_img} )); then
  #   height_img=${width_img}
  # elif (( ${width_img} < ${height_img} )); then
  #   width_img=${height_img}
  # fi
  width_img=400
  height_img=700

  rad=$( echo "0.0025 * ${width_img} * ${height_img} / 100" | bc )
  br=$( echo "${rad} * 5" | bc )
  x0=$( echo "${rad} * 3" | bc )
  y0=$( echo "${br} * 0.5" | bc )
  x1=$( echo "${x0} + ${rad}" | bc )

  declare -A arr=()
  for i in {0..2}; do
    arr[$i,0]=$x0
    arr[$i,1]=$y0
    arr[$i,2]=$x1
    arr[$i,3]=$y0
    x0=$( echo "${x0} + ${rad} * 3" | bc )
    x1=$( echo "${x0} + ${rad}" | bc )
  done

  magick ${full_file_name} -fill ${b} \
  -background ${b} \
  -gravity north -splice 0x$br \
  -draw "fill ${r}   circle ${arr[0,0]},${arr[0,1]} ${arr[0,2]},${arr[0,3]}
  fill ${y}   circle ${arr[1,0]},${arr[1,1]} ${arr[1,2]},${arr[1,3]}
  fill ${g}   circle ${arr[2,0]},${arr[2,1]} ${arr[2,2]},${arr[2,3]}" \
  ${full_file_name}
}

function convertRounded() {
  border_radius=10
  magick "${full_file_name}" \
    \( +clone -alpha extract -draw \
      "fill black polygon 0,0,0,${border_radius} ${border_radius},0 fill white circle ${border_radius},${border_radius},${border_radius},0" \
      \( +clone -flip \) -compose Multiply -composite \
      \( +clone -flop \) -compose Multiply -composite \
    \) \
    -alpha off -compose CopyOpacity -composite "${full_file_name}"
}

function convertShadow() {
  shadow_color="#000000"
  shadow_size="75x30+0+30"
  convert "${full_file_name}" \
    \( \
      +clone \
      -background "${shadow_color}" \
      -shadow "${shadow_size}" \
    \) \
    +swap \
    -background none \
    -layers merge \
    +repage "${full_file_name}"
}

function convertBorder() {
  border_color="#F8F9FA"
  #border_color="none"
  border_size=30
  magick "${full_file_name}" -bordercolor "${border_color}" -border ${border_size} "${full_file_name}"
}

function finish() {
  latest_file=`/bin/ls -th ${screenshot_dir} | head -n 1`
  size=`find ${screenshot_dir}/${latest_file} -printf %s`

  if (( ${size} == 0 || ${size} <= 20 )); then
    rm -rf "${screenshot_dir}/${latest_file}"
  fi
  notify-send "ImageMagick" "Improving success!" -t 3000
}

flameshot gui --raw > ${full_file_name}
#convertTitleBar
convertRounded
convertShadow
convertBorder
xclip -selection clipboard -i ${full_file_name} -t image/png
finish
